# $schema: https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofumpt:
      extra-rules: true
