# $schema: https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
          - gosec
      - path-except: '_test\.go'
        linters:
          - staticcheck
      - path: internal/hmac/
        text: weak cryptographic primitive
        linters:
          - gosec
      - text: "SA9003:"
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofumpt:
      extra-rules: true
