name: "GitHub Pull Request Analyser"
description: "Analyse the GitHub Pull Request"
author: "Jack Plowman"

runs:
  using: "docker"
  image: "../../../Dockerfile"
  env:
    RUNNING_IN_GITHUB_ACTION: "true"
