# labels auto assigned to PR, keep in sync with labels.yml
dependencies:
  - pyproject.toml
  - poetry.lock
go:
  - "*.go"
github-pages:
  - github-pages/**
  - github-pages/**/*
just:
  - Justfile
  - "*.just"
automation:
  - .github/*
  - .github/**/*
