name: "Setup Go Dependencies"
description: "Sets up Go dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod
    - name: Set up Just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
