name: "Test Action"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Action
        uses: ./
        with:
          github_repository_owner: ${{ github.repository_owner }}
          github_repository: ${{ github.repository }}
          github_pr_number: ${{ github.event.number }}
          github_token: ${{ secrets.GH_TOKEN }}
